### ISSUE TITLE
Setting cell settings

### ISSUE THREAD

**Issue by pauljgasper** [jdhuang-csm/pygamry#1]
Trying to get this to work using some of my Gamry's. I can't find a way to set the cell settings, i.e., full/half cell, positive side is working or counter electrode, ..., like you can in the Gamry Framework.

On my own cells so far, the instrument is being detected correctly, and something is running, but the resulting measurement (just OCP so far) is not correct.

C:/Users/pgasper/AppData/Local/anaconda3/envs/gamry/python.exe c:/Users/pgasper/Documents/GitHub/pygamry/measure_scripts/measure_ocp.py C:\\Users\\pgasper\\Documents\\gamry_data test                       
('IFC5000-07537',)
Beginning cycle 0
-----------------------------
Running OCV
init time: 0.319
running
0
Received KeyboardInterrupt
PumpEvents done
dtaq run time: 25.917 s
Final write time: 0.000
loop time: 25.918
Cleanup time: 0.050
Run time: 25.97 s
OCV done

OCV: -2.825 V

**Comment by jdhuang-csm** [comment]
Hey Paul,

I never actually adjusted those settings in Framework, so I didn't do anything with them in pygamry. However, I'm pretty sure that they can be configured - I just need to have a look at Gamry's documentation to find it. Is the OCV that you measured stable and correct with a sign change, or is it nonsense?

**Comment by pauljgasper** [comment]
The OCV measured is stable but not close to correct - it should be ~3.2 V (partially discharged LFP/Gr cell).

Actually, one thought that occurs to me is that I was using a Gamry 5000E. This uses different voltage leads than the Gamry 1000 series potentiostats (5000 series use the orange lead for the counter electrode voltage, rather than the white lead). So maybe it was measuring voltage between the wrong leads. I'm guessing this configuration is done automatically in Gamry Framework when it detects a 5000E. I'll check on my end if I get the correct voltage measurement when using the white lead instead of the orange lead.

**Comment by pauljgasper** [comment]
FYI that was the issue. So just something to note somewhere in documentation:
"Note that pygamry always uses the lead conventions from low-current potentiostats like the 1000E, specifically, the white lead as the counter electrode voltage sense. For higher current potentiostats with separated current and voltage leads, like the 5000E, the Gamry framework autodetects the hardware and switches the default counter electrode voltage sense to the orange lead. When using pygamry, instead use the white lead as the counter electrode voltage, pygamry does not yet autodetect the type of potentiostat and adjust the settings yet."

**Comment by jdhuang-csm** [comment]
Thanks for the info! I had a chance to review the documentation and I didn't find anything that looks like it would control which leads are used or to specify full/half cell. You can change the current sign convention using IGamryPstat.SetIConvention, but I'm not sure how useful this is.  I'll add a note to the README.

**Comment by jdhuang-csm** [comment]
Closing this since I do not think a solution is possible with Electrochemistry Toolkit, but if you find anything that suggests otherwise, let me know.
